#!/usr/bin/env python3
"""
Render TUI doc snapshot HTML sections into PNG files.

Reads target/tui-doc-snapshots/index.html (generated by cargo run --bin tui-doc-snapshots),
parses each <section> terminal block, and writes one PNG per section into docs/images/tui/.

Usage:
    python3 scripts/render-tui-snapshots.py
"""

import re
import sys
import html as html_module
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# ── paths ──────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
HTML_SRC = REPO_ROOT / "target" / "tui-doc-snapshots" / "index.html"
OUT_DIR = REPO_ROOT / "docs" / "images" / "tui"

# ── visual constants ───────────────────────────────────────────────────────────
FONT_PATH_REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FONT_PATH_BOLD    = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
FONT_SIZE = 18          # px
LINE_HEIGHT = 22        # px – matches the CSS line height
CHAR_WIDTH = 11         # px – approximate for DejaVu Sans Mono at 18px
H_PAD = 16             # card horizontal padding
V_PAD = 16             # card vertical padding
BG_COLOR = "#1f1f1f"    # terminal background (matches CSS .screen)
DEFAULT_FG = "#d4d4d4"  # default foreground

# ── helpers ────────────────────────────────────────────────────────────────────

def hex_to_rgb(hexstr: str):
    h = hexstr.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


def parse_screen(pre_html: str) -> list[list[tuple[str, tuple, bool]]]:
    """
    Parse a <pre class="screen">…</pre> inner HTML into a list of lines.
    Each line is a list of (char, rgb_tuple, bold) tuples.

    The HTML structure is:
        <span class="line"><span style="…">X</span><span style="…">Y</span>…</span>
    The outer line span contains nested character spans, so we split on the
    opening tag first to avoid the non-greedy .*? stopping at the first </span>.
    """
    lines: list[list[tuple[str, tuple, bool]]] = []

    # Split on line-span openings; skip the first (empty) chunk before the first tag
    for line_chunk in pre_html.split('<span class="line">')[1:]:
        cells: list[tuple[str, tuple, bool]] = []

        # Each inner span carries one character with optional style
        for span_match in re.finditer(r'<span(?:\s+style="([^"]*)")?>(.*?)</span>', line_chunk):
            style_str = span_match.group(1) or ""
            char_html = span_match.group(2)
            char = html_module.unescape(char_html)
            if not char:
                continue

            # parse color
            color_match = re.search(r'color:\s*(#[0-9a-fA-F]{6})', style_str)
            fg = hex_to_rgb(color_match.group(1)) if color_match else hex_to_rgb(DEFAULT_FG)

            bold = "font-weight:700" in style_str or "font-weight: 700" in style_str

            cells.append((char, fg, bold))

        lines.append(cells)

    return lines


def render_lines_to_png(lines: list[list[tuple[str, tuple, bool]]], out_path: Path):
    try:
        font_reg  = ImageFont.truetype(FONT_PATH_REGULAR, FONT_SIZE)
        font_bold = ImageFont.truetype(FONT_PATH_BOLD, FONT_SIZE)
    except IOError as e:
        print(f"  Font load error: {e}", file=sys.stderr)
        sys.exit(1)

    num_lines = len(lines)
    num_cols  = max((len(row) for row in lines), default=0)

    img_w = num_cols * CHAR_WIDTH + 2 * H_PAD
    img_h = num_lines * LINE_HEIGHT + 2 * V_PAD

    img = Image.new("RGB", (img_w, img_h), hex_to_rgb(BG_COLOR))
    draw = ImageDraw.Draw(img)

    for row_idx, row in enumerate(lines):
        y = V_PAD + row_idx * LINE_HEIGHT
        for col_idx, (char, fg, bold) in enumerate(row):
            x = H_PAD + col_idx * CHAR_WIDTH
            font = font_bold if bold else font_reg
            draw.text((x, y), char, font=font, fill=fg)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(str(out_path), "PNG")


# ── main ───────────────────────────────────────────────────────────────────────

def main():
    if not HTML_SRC.exists():
        print(f"Error: {HTML_SRC} not found.", file=sys.stderr)
        print("Run: cargo run --bin tui-doc-snapshots", file=sys.stderr)
        sys.exit(1)

    raw = HTML_SRC.read_text(encoding="utf-8")

    # Find all <section class="snapshot-card" id="…"> blocks
    section_re = re.compile(
        r'<section[^>]+id="([^"]+)"[^>]*>.*?<pre class="screen">(.*?)</pre>',
        re.DOTALL
    )

    found = 0
    for m in section_re.finditer(raw):
        section_id = m.group(1)
        pre_inner  = m.group(2)
        out_path   = OUT_DIR / f"{section_id}.png"

        print(f"Rendering {section_id} → {out_path.relative_to(REPO_ROOT)}")
        lines = parse_screen(pre_inner)
        if not lines:
            print(f"  Warning: no lines parsed for {section_id}", file=sys.stderr)
            continue
        render_lines_to_png(lines, out_path)
        found += 1

    if found == 0:
        print("Error: no sections found in HTML.", file=sys.stderr)
        sys.exit(1)

    print(f"\nWrote {found} PNG(s) to {OUT_DIR.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
